language: python
python:
  - "2.6"
  - "2.7"
install:
  - pip install -r test-requirements.txt --use-mirrors --upgrade
  - pip install coveralls --use-mirrors
script: nosetests --with-coverage --cover-package=pysrt
after_success:
  coveralls
